### ISSUE TITLE
Number of elements and other notes

### ISSUE THREAD

**Issue by martin1cerny** [anborr/LOIN-XML-Schema#8]
Here are my notes from the call on 01/12/2022. I'll send a PR to address some of them.

LevelOfInformationNeed - only one specification per XML file?

Prerequisities - just strings? Should use keys? References to external resources?
InformationDeliveryMilestone - is it how we call it?

SpecificationPerObjectType.ObjectType has 'Name' only - is it type (IfcWall), or name ('Brick wall with render')
SpecificationPerObjectType.ObjectType is optional?

SpecificationPerObjectType.Documentation - only one?
SpecificationPerObjectType.GeometricalInformation - only one?
SpecificationPerObjectType.AlphanumericalInformation - only one DT?

SpecificationPerObjectType.AlphanumericalInformation.IsDataTemplateFor - mandatory link to T_ConstructionObject. Might be conflicting with SpecificationPerObjectType.ObjectType?

SpecificationPerObjectType.UUID - shall we reuse the definition from 23387: T_UUID?

How do we define value requirement for a property?
T_PredefinedValues = list of valid options?
T_PredefinedValue.Value is a string!   "55.5 m/s", "55.2 ms-1", "55,5 m s-1", "000,055.55 m · s⁻¹", "000.055,55"

RequiredDocument.purpose - duplicate of Prerequisites.purpose?

**Comment by jakob-beetz** [comment]
Hi Martin, 

thank you very much for your contributions! These are very valuable, we will integrate and address your points. 
I you have time and energy, you are of course also invited to submit patches 

Looking forward to further disussions!

**Comment by anborr** [comment]
Sub-issues have been created as separated issues #11 #12 #13 #14 #15 #16 #17.
